[package]
name = "smollink"
version = "0.1.0"
edition = "2024"


[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
reqwest = { version = "0.12.1", features = ["json"] }
tokio = { version = "1.36.0", features = ["full"] }
